server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin: # Zipkin Tracing Server. It connects to the Zipkin server docker image
    base-url: http://localhost:9411

eureka: # Eureka Server
  client:
    fetch-registry: false
    register-with-eureka: false